In [5]:
import numpy as np
a = np.array([20,40,60,80])
print(np.append(a,90))
b = np.array([[20,40],[60,80]])
print(np.append(b,[90,100]))

[20 40 60 80 90]
[ 20  40  60  80  90 100]


In [15]:
print(np.insert(a,1,50)) #array, index, value
print(np.insert(b,1,[50,100],axis=0))
print(np.insert(b,1,[50,100],axis=1))

[20 50 40 60 80]
[[ 20  40]
 [ 50 100]
 [ 60  80]]
[[ 20  50  40]
 [ 60 100  80]]


In [20]:
print(np.delete(a,1))
print(np.delete(b,1)) # 2D becomes 1D array
print(np.delete(b,1,axis=0))
print(np.delete(b,1,axis=1))

[20 60 80]
[20 60 80]
[[20 40]]
[[20]
 [60]]
