In [8]:
import numpy as np
a = np.array([20,40,60,80])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a)) #mean formula - sum of elements/ no. of elements = 200/4
print(np.cumsum(a)) #cummulative sum
print(np.cumprod(a)) #cummulative product

200
20
80
4
50.0
[ 20  60 120 200]
[     20     800   48000 3840000]


In [28]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
print(np.sum(price))
print(np.cumsum([price,quantity]))
c = np.cumprod([price,quantity],axis=0)
print(c)
print(c[1].sum)

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
1029
[ 100  250  449  649  899 1029 1039 1089 1119 1159 1189 1199]
[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
<built-in method sum of numpy.ndarray object at 0x0000028EBDBA03F0>
