In [1]:
print("Hello")

Hello


In [4]:
print("Hi")

Hi


In [25]:
import numpy as np
a = [[30,40,20],[40,60,10]]
arr = np.array(a) # converting list to array
print(arr)
print(np.shape(arr))
print(np.size(arr))
print(len(a))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 20]
 [40 60 10]]
(2, 3)
6
2
<class 'numpy.ndarray'>
int64
[[30. 40. 20.]
 [40. 60. 10.]]


In [33]:
import numpy
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1+arr2)
print(np.add(arr1,arr2))
#####2-dimensional array###########
arr3 = np.array([[30,40],[20,10]])
arr4 = np.array([[30,20],[10,20]])
print(arr3+arr4)
print(np.add(arr3,arr4))

[60 60 70 40 30]
[60 60 70 40 30]
[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [35]:
import numpy
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])
print(arr1-arr2)
print(np.subtract(arr1,arr2))
#####2-dimensional array###########
arr3 = np.array([[30,40],[20,10]])
arr4 = np.array([[30,20],[10,20]])
print(arr3-arr4)
print(np.subtract(arr3,arr4))

[  0  20  50   0 -10]
[  0  20  50   0 -10]
[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [38]:
#####2-dimensional array###########
arr3 = np.array([[30,40],[20,10]])
arr4 = np.array([[30,20],[10,20]])
print(arr3*arr4)
print(np.multiply(arr3,arr4))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [40]:
#####2-dimensional array###########
arr3 = np.array([[30,40],[20,10]])
arr4 = np.array([[30,20],[10,20]])
print(arr3/arr4)
print(np.divide(arr3,arr4))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [48]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.exp(arr1))
print(np.pow(arr1,arr2))
arr3 = np.array([9,16,4,1])
print(np.sqrt(arr3))

[20.08553692 54.59815003  7.3890561   2.71828183]
[ 9 16  4  1]
[3. 4. 2. 1.]
