In [2]:
list1 = [30,40,50]
list2 = [5,5,3]
print(list1+list2) # concatention

[30, 40, 50, 5, 5, 3]


In [5]:
import numpy as np
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [26]:
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))
print(np.concatenate([arr1,arr2],axis=1))
#print(np.concatenate([arr1,arr2],axis=2)) 
#AxisError: axis 2 is out of bounds for array of dimension 2

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]
[[30 40  5  5]
 [50 10  3  3]]


In [13]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [14]:
print(np.vstack([arr1,arr2])) #vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [23]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,4)
print(b)
print(b[1])
print(np.array_split(a,5))

[array([20, 40]), array([30, 40]), array([10]), array([20])]
[30 40]
[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [24]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,3)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64)]
